### ISSUE TITLE
Improve look of workspaces section.

### ISSUE THREAD

**Issue by sakshamsharma** [travitch/taffybar#145]
I came across a window manager called qtile written in Python. It's statusbar has a really nice looking workspace section. The whole thing is quite inspired by Xmonad BTW.
It'd be great if someone can convert the simple textual printing of workspace names to something like this ->
![qtile](http://www.qtile.org/static/img/screenshots/default.png)

Not sure if GTK has something like this.

**Comment by travitch** [comment]
If you mean having a nice background color for the active workspace instead of just brackets, I think it might be possible with the current pager.  See the `PagerConfig` System.Taffybar.Pager.hs.  For example, I think you could probably emulate what you see in qtile with `myPagerConfig = defaultPagerConfig { activeWorkspace = colorize "white" "blue" . escape }`

That should color the background of the active workspace blue.  Note, I have not tried to play with this very much, but that was the intent.  Let me know if it doesn't work and I can poke at it.

**Comment by jokogr** [comment]
@travitch xmobar has an additionalFonts parameter, where one could include Font Awesome and have icons in the workspace pager. Is there anything similar in Taffybar?

**Comment by travitch** [comment]
I'm not exactly sure how Font Awesome works.  If it is just a normal TTF/OTF font, it should be possible.

All of the labels in taffybar support pango markup (see https://developer.gnome.org/pango/stable/PangoMarkupFormat.html).  The format looks a little bit like HTML.  You can specify fonts, font sizes, colors, and more for spans of text.

**Comment by IvanMalison** [comment]
I would argue that #180 addresses this, no?

**Comment by sakshamsharma** [comment]
Well, somewhat yes. I'd still like this issue to stay open. Gradient/Transparent backgrounds (they were there in an unmerged PR I think), rounded edges, such things *might* appeal to some people.

**Comment by IvanMalison** [comment]
@sakshamsharma #237 adds all the gtk features that you want as you can use css styling on gtk widgets to get all of the three things you mentioned.
