### ISSUE TITLE
Bar is white since a recent update.

### ISSUE THREAD

**Issue by Profpatsch** [travitch/taffybar#146]
My taffybar turned white after a recent update:

![screenshot](https://cloud.githubusercontent.com/assets/3153638/13540500/391e93d0-e257-11e5-9454-f697d85d9c34.png)

Is that a design decision? I looked at the config again, but I didn’t find a way to set the color.

**Comment by sakshamsharma** [comment]
It happened since #131 . I had commented this there too. I'm forced to use a theme with black title bars since then (alternatively, I used to undo that commit locally and build taffybar again locally from source).

**Comment by Profpatsch** [comment]
Reverse-applying the patch worked, thanks. But it would be nice to have an official way to change the color.

**Comment by travitch** [comment]
The core of this problem is that xsettings managers (e.g., gnome-settings-daemon) override theme settings taken from gtkrc files.  My impression of #131 was that choosing some new names for color entries would help, but I haven't been testing thoroughly.

I'll try to take a look at it, but I haven't been running an xsettings manager, so I don't notice when these things break.

**Comment by Profpatsch** [comment]
I don’t run one, too, as far as I know.

**Comment by rlbdv** [comment]
In case it helps, this just happened to me, and it turns out it that's because I accidentally forgot to change the session type back to xmonad in lightdm after some other login used Xfce (looks like lightdm doesn't remember the last session type for each user).  Switching back to an xmonad session fixed the problem.

**Comment by sakshamsharma** [comment]
That is probably one scenario. I for one don't use any login manager (simply do startx), yet I have this issue.

**Comment by Profpatsch** [comment]
In #131 the .rc file is changed with some color names. I’m not quite sure what that file does, though, or even where the syntax comes from.

**Comment by sakshamsharma** [comment]
Does someone know a way to bypass this without changing the source? I do not want my system Gtk theme to be overriding what I have set in the taffybar.rc file, that's what the rc file was supposed to be for.

I have been using this patch:
```
diff --git a/src/System/Taffybar.hs b/src/System/Taffybar.hs
index c6665c1..3e3c1ef 100644
--- a/src/System/Taffybar.hs
+++ b/src/System/Taffybar.hs
@@ -267,8 +267,9 @@ taffybarMain cfg = do
   -- Load default and user gtk resources
   defaultGtkConfig <- getDefaultConfigFile "taffybar.rc"
   userGtkConfig <- getUserConfigFile "taffybar" "taffybar.rc"
-  rcParse defaultGtkConfig
-  rcParse userGtkConfig
+  rcSetDefaultFiles [ defaultGtkConfig, userGtkConfig  ]
+  {-rcParse defaultGtkConfig-}
+  {-rcParse userGtkConfig-}
```

But it is more of hassle than I'd care.

**Comment by dlahoti** [comment]
Changing `"default"` to `"taffybar-default"` in both its occurences in `taffybar.rc` fixes it for me.

**Comment by IvanMalison** [comment]
This issue is no longer relevant since the theming system has switched to CSS as of #237
