### ISSUE TITLE
WorkspaceHUD show the icons of the windows visible on all screens in the selected workspace

### ISSUE THREAD

**Issue by igwan** [travitch/taffybar#239]
I have two monitors so two workspaces visible, workspaceHUD will show the windows icons of both visible workspaces inside the selected one (and none in the deselected one).

My config doesn't differ much from the example one but it might still be something on my end. Are some of you using multiple monitors and getting the correct behavior ? Or is workspaceHUD not tested with multiple monitors ?

**Comment by IvanMalison** [comment]
Hi @igwan I use WorkspaceHUD on 3 monitors and I get the correct behavior.

I'm not quite sure I understand the behavior you are describing. You say that the window icons are "visible in the selected one". I'm not quite sure what you mean by selected one here, but I suppose the most reasonable interpretation is:

The workspace widgets for both visible workspaces display the icons of the windows contained in them on the taffybar window that is displayed on the monitor that currently has focus, while no window icons are visible at all on the window that does not have focus.

Is that correct?

If so, that is certainly strange, but I would point out that the expected behavior of WorkspaceHUD is that it should look identical on both taffybar windows. WorkspaceHUD does not currently support identifying which workspace is currently being displayed on the monitor that its containing taffy window is displayed on. I do plan to add support for this sometime soon though.

**Comment by igwan** [comment]
Yeah, sorry, I was quite tired and could have been a lot clearer.

By « the selected one » I meant the workspace with the currently focused window.

Actually taffybar on both monitors looks exactly the same. I will provide some screenshots to clear things out.
I don't recall if those are the default colors but here green is the focused workspace and yellow is visible.

- chromium in workspace 1, urxvt in workspace 2, workspaces 3 and 4 are visible.
  Everything is fine.
![1](https://i.imgur.com/dkQEO5C.png)

- now workspaces 1 and 2 are visible with focus being on 2. I didn't move anything between workspaces, chromium is still in workspace 1 and urxvt in 2 but they are both shown in workspace 2.
  ![2](https://i.imgur.com/xsrd73n.png)

- same workspaces visible, switching focus one workspace 1. Still nothing moved between workspaces. Both windows are shown in workspace 1.
  ![3](https://i.imgur.com/DzmNcAE.png)

- now focusing workspace 2 and 3, focus is on 3. Urxvt is shown in workspace 3 but he never moved from the 2.
  ![4](https://i.imgur.com/xOV6ft6.png)

[Here](https://imgur.com/a/4ct0c) is an album with the non cropped screenshots in case actually seeing both monitors and windows helps out.

**Comment by IvanMalison** [comment]
@igwan Oh wow, that is really strange.

Is it just the active window that gets moved, or all windows in the active workspace?

You are using XMonad, right? What version are you using?

**Comment by igwan** [comment]
Every windows of the visible unfocused workspace are shown in the focused workspace widget.

This is with XMonad 0.13, both taffybar and XMonad are built with stack using cabal and stack files taken from your own dotfiles (btw thanks for all the amazing work). 
I only changed `xmonad/stack.yaml` to require xmonad and xmonad-contrib as extra-deps instead of having them as git submodules and moved gtk-traymanager to an extra-deps in both taffybar and xmonad `stack.yaml`.

I originally tried your gtk3 branch and got the same behaviour.

**Comment by IvanMalison** [comment]
@igwan hmm okay, can you try turning on debug mode for workspaceHUD. and then clicking on the log widget and pasting some of the output back here?

**Comment by IvanMalison** [comment]
@igwan Before you do that, could you download the wmctrl utility and paste the output of wmctrl -l when the workspaces are in the wrong place in workspaceHUD?

**Comment by IvanMalison** [comment]
@igwan Also, if you have your dots in source control if you could post those that would also be helpful.

**Comment by igwan** [comment]
I just tried `wmctrl -l` and it also showed the windows on the wrong workspace. So I guess this is not related to taffybar but to my own `xmonad.hs`. Something related to ewmh because xmobar worked fine.
Anyway sorry about that, I will investigate further tomorrow.

**Comment by IvanMalison** [comment]
> I just tried wmctrl -l and it also showed the windows on the wrong workspace. So I guess this is not related to taffybar but to my own xmonad.hs. Something related to ewmh because xmobar worked fine.
> Anyway sorry about that, I will investigate further tomorrow.

@igwan Seems like you figured out where I was headed with that.

This might not be relevant, but I do run a custom version of xmonad that has changes to the ewmh desktops code.

**Comment by IvanMalison** [comment]
@igwan Oh holy crap, I figured it out. 

Check out https://github.com/IvanMalison/xmonad-contrib/blob/89a0fdf7fe6861a4ce57de6a375a0b71c612f49a/XMonad/Hooks/EwmhDesktops.hs#L98

So I actually refactored all of that code there because it was total garbage and nobody igves a fuck about gnome panel. If you use my custom version of xmonad-contrib, it wont do this...

**Comment by igwan** [comment]
Yep, it works using your version of xmonad-contrib. Very nice.
Thanks a lot for your help.
