### ISSUE TITLE
Taffybar does not hide on ToggleStruts

### ISSUE THREAD

**Issue by n-buck** [travitch/taffybar#257]
Hi
I am not sure if it is an issue from taffybar but I do not know where else to ask for help.
My problem is the following:
When ever I'd like to hide taffybar, it is still visible.
I already tried to restart feh, hoping the wallpaper would override the bar, but it does not work. Taffybar also updates in the background.

Here I have the pictures:
[No Struts and no fulscreen](https://ibb.co/dmFDvS)
[With struts and no fulscreen](https://ibb.co/mcdGFS)
[No struts and fulscreen](https://ibb.co/f6T59n)
So what I am looking for, is a way to completely hide taffybar when I toggleStruts.
My config is on git, and any help is appreciated.

Tanks in advance and keep on the great work

**Comment by IvanMalison** [comment]
How are you attempting to toggleStruts? are you using the dbus command?

**Comment by IvanMalison** [comment]
Ah @n-buck I assume you are referring to the xmonad layout modifier ToggleStruts. I think you may be misunderstanding what ToggleStruts is supposed to do. As i understand it, ToggleStruts is a way to control whether or not XMonad will keep windows out of the way of any struts that are present, and what you toggle is whether xmonad does this or not, so it is not surprising that the taffybar window is still visible underneath your other windows.

If what you want is to be able to show and hide taffybar, you'll need to do that through taffybar. You're in luck, because there is a module (ToggleMonitor) that will do exactly what you want! Let me know if you need any help getting it set up.

You can refer to my configuration here:

https://github.com/IvanMalison/dotfiles/blob/5db0fec9b7d9685cf2a9cdac5831b0615b395973/dotfiles/config/taffybar/taffybar.hs#L267

**Comment by n-buck** [comment]
@IvanMalison 
Currently I installed taffybar through the AUR. In this version I can' t access the ToggleMonitor module.
I tried to import it manually but it seems I can't import Paths_taffybar.

So I guess the easiest way to get this working is to install taffybar through cabal or stack.
Is there any documentation for this module? I found nothing on [https://hackage.haskell.org/package/taffybar](https://hackage.haskell.org/package/taffybar).

**Comment by IvanMalison** [comment]
You can try: https://github.com/travitch/taffybar/blob/master/quick-start.sh

**Comment by n-buck** [comment]
I managed to get it running with a little help from issue #215.
Thank you, you have been a great help!

**Comment by nomeata** [comment]
@n-buck, what exactly solved this for you?

In my setup, it _used_ to be the case that `ToggleStruts` would allow the normal windows to fill the full screen (on top of taffybar), but _something_ broke that, and I am wondering what it might be.

**Comment by IvanMalison** [comment]
@nomeata did you upgrade xmonad or xmonad contrib recently?

Based on the issue that @n-buck linked, it sounds like he might have simply decided that having the ability to manually toggle taffybar on and off solved his problem adequately.

Do you know around when ToggleStruts stopped working for you?

**Comment by IvanMalison** [comment]
@nomeata I just made an AVOIDSTRUTS multi toggle in my xmonad config and it works pretty flawlessly.

Pretty much the same things as ToggleStruts just a bit more general

https://github.com/IvanMalison/dotfiles/commit/4db7617ad62041dc465c44f0a5b31e1ff09ff978

**Comment by nomeata** [comment]
> Do you know around when ToggleStruts stopped working for you?

Most likely when I switched to NixOS, so that is pretty broad, and likely includes an upgrade of both

**Comment by nomeata** [comment]
Heh, suddenly it works again. Maybe it is a question of when windows are created/added/deleted/raised/something like that. I’ll keep an eye out.

**Comment by IvanMalison** [comment]
@nomeata ah question: when you togglestruts, do the windows correctly move up so that they are partially obscured by taffybar, so they are in fact avoiding the strut, but taffybar is simply drawn over them?

If that is the case, it could be something I have occasionally seen before. We do this in gtk-strut: (https://github.com/IvanMalison/gtk-strut/blob/84a96d51ff4a50675789ed0954836f6ab81b0d27/src/Graphics/UI/GIGtkStrut.hs#L128) so this should not happen in theory, but sometimes it seems that the XServer's notion of who is on top of whom somehow gets messed up.

**Comment by nomeata** [comment]
> do the windows correctly move up so that they are partially obscured by taffybar, so they are in fact avoiding the strut, but taffybar is simply drawn over them?

Yes, that’s what I observe. Sorry for being unclear

**Comment by n-buck** [comment]
> 
> 
> @n-buck, what exactly solved this for you?
> 
> In my setup, it _used_ to be the case that `ToggleStruts` would allow the normal windows to fill the full screen (on top of taffybar), but _something_ broke that, and I am wondering what it might be.

Hello @nomeata 
I have set xmonad up to send the d-bus command `spawn "dbus-send --print-reply=literal --dest=taffybar.toggle /taffybar/toggle taffybar.toggle.toggleCurrent"` directly.
But glad to hear that it works for you again.

**Comment by IvanMalison** [comment]
I think this may be a known issue: https://github.com/xmonad/xmonad-contrib/issues/211

**Comment by nomeata** [comment]
@n-buck: I get
```
Error org.freedesktop.DBus.Error.ServiceUnknown: The name taffybar.toggle was not provided by any .service files
```
Did I install taffybar wrong? Is there a corresponding taffybar plugin that’s needed?

**Comment by n-buck** [comment]
@nomeata 
I beleave it comes from the ToggleMonitor module:
```
import System.Taffybar.ToggleMonitor
...
withToggleSupport taffyConfig
```
My config is really old, so it may work otherwise now.

**Comment by nomeata** [comment]
Thanks! It’s called [System.Taffybar.DBus.Toggle](https://hackage.haskell.org/package/taffybar-3.3.0/docs/System-Taffybar-DBus-Toggle.html) now, but then it works. And it’s actually nicer than `ToggleStruts`, because this allows me to fully hide taffybar even when there is nothing obscuring it (e.g. in a zen-focus-layout)
