### ISSUE TITLE
TaffyPager does not honor widgetSpacing

### ISSUE THREAD

**Issue by joyfulmantis** [travitch/taffybar#53]
TaffyPager ignores widgetSpacing. Specifically when I set the widgetSpacing to 0, the spacing between the workspace names is not 0

**Comment by cumgun** [comment]
+1

**Comment by cumgun** [comment]
@IvanMalison thanks a lot for your update. Would you be able to provide a configuration example?

**Comment by IvanMalison** [comment]
@cumgun Yes, of course. You'll need to have taffybar installed from the git repository since there has not been a release that has included these changes yet.

You'll need to set up both a taffybar.hs and a taffybar.rc.

You can check out my configuration [here](https://github.com/IvanMalison/dotfiles/tree/master/dotfiles/config/taffybar)

I'll post a more minimal example here in a second.

**Comment by IvanMalison** [comment]
@cumgun Here is a minimal taffybar.hs, taffybar.rc pair 

hs: https://gist.github.com/IvanMalison/8359d4a2e8ee2bc5214cca79b7d1e09a
rc: https://gist.github.com/IvanMalison/eb8ca91bb9db418742b730aeb620b71b

that should accomplish exactly what this ticket would seem to want

Here's an image

http://i.imgur.com/SggNcKV.png

**Comment by cumgun** [comment]
@IvanMalison awesome, thanks a lot for your time and effort! This indeed achieves exactly what I wanted to see.
